services:
  frontend:
    image: ghcr.io/jbolonski/poollog-frontend:latest
    pull_policy: always
    depends_on:
      - backend
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.poollog-frontend.entrypoints=http"
      - "traefik.http.routers.poollog-frontend.rule=Host(`poollog.docker.jbolo.net`) && !PathPrefix(`/api`)"
      - "traefik.http.middlewares.poollog-frontend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.poollog-frotnend.middlewares=meshmonitor-https-redirect"
      - "traefik.http.routers.poollog-frontend-secure.entrypoints=https"
      - "traefik.http.routers.poollog-frontend-secure.rule=Host(`poollog.docker.jbolo.net`)"
      - "traefik.http.routers.poollog-frontend-secure.tls=true"
      - "traefik.http.routers.poollog-frontend-secure.service=poollog-frontend"
      - "traefik.http.services.poollog-frontend.loadbalancer.server.port=80"

  backend:
    image: ghcr.io/jbolonski/poollog-backend:latest
    pull_policy: always
    environment:
      PORT: 3001
      POOLLOG_DATA_PATH: /data/entries.json
    networks:
      - proxy
      - poolnet
    volumes:
      - poollog-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.poollog-api.entrypoints=http"
      - "traefik.http.routers.poollog-api.rule=Host(`poollog.docker.jbolo.net`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.poollog-api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.poollog-api.middlewares=meshmonitor-https-redirect"
      - "traefik.http.routers.poollog-api-secure.entrypoints=https"
      - "traefik.http.routers.poollog-api-secure.rule=Host(`poollog.docker.jbolo.net`)"
      - "traefik.http.routers.poollog-api-secure.tls=true"
      - "traefik.http.routers.poollog-api-secure.service=poollog-api"
      - "traefik.http.services.poollog-api.loadbalancer.server.port=3001"

volumes:
  poollog-data:

networks:
  proxy:
      external: true
  poolnet:
      driver: bridge